tweets <- read.csv("D:/Data/tweets.csv", stringsAsFactors=FALSE)
reviews_text<- paste(tweets$Tweet_Date.Tweet_Text.Tweet_Handle,collapse = "  ")
review_source<- VectorSource(reviews_text)
corpus<-Corpus(review_source)
corpus<- tm_map(corpus,content_transformer(tolower))
corpus<- tm_map(corpus,removePunctuation)
corpus<- tm_map(corpus,stripWhitespace)
corpus<- tm_map(corpus,removeWords,stopwords("english"))
dtm <-DocumentTermMatrix(corpus)
dtm2<- as.matrix(dtm)
frequency <-colSums(dtm2)
frequency <-sort(frequency,decreasing = TRUE)
library(wordcloud)
words<- names(frequency)
wordcloud(words[1:100], frequency[1:100])
